site_name: DCMspec Documentation

# NOTE: The API Reference section uses logical ordering (by functional area and workflow)
# rather than alphabetical order. This is to help users find related concepts together
# and to reflect the typical usage flow of the library.
nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration & Caching: configuration.md
  - CLI Applications:
      - CLI Overview: cli/index.md
      - modattributes: cli/modattributes.md
      - iodattributes: cli/iodattributes.md
      - iodmodules: cli/iodmodules.md
      - dataelements: cli/dataelements.md
      - uidvalues: cli/uidvalues.md
      - upsdimseattributes: cli/upsdimseattributes.md
      - upsioddimseattributes: cli/upsioddimseattributes
      - tdwiimoddefinition: cli/tdwiimoddefinition.md

  - API Reference:
      - API Overview: api/index.md
      - Constants Modules:
          - Service Attribute Defaults: api/service_attribute_defaults.md
      - Core Classes:
          - SpecModel: api/spec_model.md
          - SpecMerger: api/spec_merger.md
          - ServiceAttributeModel: api/service_attribute_model.md
          - SpecFactory: api/spec_factory.md
          - IODSpecBuilder: api/iod_spec_builder.md
      - Parse Classes:
          - SpecParser: api/spec_parser.md
          - DOMTableSpecParser: api/dom_table_spec_parser.md
          - CSVTableSpecParser: api/csv_table_spec_parser.md
      - Load Classes:
          - DocHandler: api/doc_handler.md
          - XHTMLDocHandler: api/xhtml_doc_handler.md
          - UPSXHTMLDocHandler: api/ups_xhtml_doc_handler.md
          - PDFDocHandler: api/pdf_doc_handler.md
      - Store Classes:
          - SpecStore: api/spec_store.md
          - JSONSpecStore: api/json_spec_store.md
      - Print Classes:
          - SpecPrinter: api/spec_printer.md
          - IODSpecPrinter: api/iod_spec_printer.md
      - Utils Classes:
          - Config: api/config.md
          - DOMUtils: api/dom_utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_section_style: spacy
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - def_list

extra_css:
  - css/mkdocstrings.css
